### ISSUE TITLE
Mysterious crash, recently caused by libfm-qt

### ISSUE THREAD

**Issue by tsujan** [lxde/pcmanfm-qt#540]
Very sorry for this poor report! I don't know why the crash happened, let alone how to reproduce it. I opened this issue to investigate it later. This is the backtrace:
````
#0  0x00007f8268fd0014 in  () at /usr/lib/libfm-qt.so.3
#1  0x00007f8268fd0527 in  () at /usr/lib/libfm-qt.so.3
#2  0x00007f8268fd0bfb in  () at /usr/lib/libfm-qt.so.3
#3  0x00007f8268fc6357 in  () at /usr/lib/libfm-qt.so.3
#4  0x00007f8268fc896c in  () at /usr/lib/libfm-qt.so.3
#5  0x00007f8268fc85bb in  () at /usr/lib/libfm-qt.so.3
#6  0x00007f8268fc8bf1 in  () at /usr/lib/libfm-qt.so.3
#7  0x00007f8268fc9d1e in  () at /usr/lib/libfm-qt.so.3
#8  0x00007f8268feca9d in Fm::FolderMenu::FolderMenu(Fm::FolderView*, QWidget*) () at /usr/lib/libfm-qt.so.3
#9  0x00007f8268fdff02 in Fm::FolderView::onFileClicked(int, std::shared_ptr<Fm::FileInfo const> const&) ()
    at /usr/lib/libfm-qt.so.3
#10 0x000000000043de4b in  ()
#11 0x00007f82679528af in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#12 0x00007f8269023b93 in Fm::FolderView::clicked(int, std::shared_ptr<Fm::FileInfo const> const&) ()
    at /usr/lib/libfm-qt.so.3
#13 0x00007f8268fdd85d in Fm::FolderView::emitClickedAt(Fm::FolderView::ClickType, QPoint const&) ()
    at /usr/lib/libfm-qt.so.3
#14 0x00007f8268fe1627 in Fm::FolderView::contextMenuEvent(QContextMenuEvent*) () at /usr/lib/libfm-qt.so.3
#15 0x00007f826868cb8b in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
#16 0x00007f8268649e4c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#17 0x00007f82686526d0 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#18 0x00007f8267922bd0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#19 0x00007f82686a7093 in  () at /usr/lib/libQt5Widgets.so.5
#20 0x00007f82686a9691 in  () at /usr/lib/libQt5Widgets.so.5
#21 0x00007f8268649e4c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#22 0x00007f8268651926 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#23 0x00007f8267922bd0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#24 0x00007f8267e851e4 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
    at /usr/lib/libQt5Gui.so.5
#25 0x00007f8267e86d46 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/libQt5Gui.so.5
#26 0x00007f8267e5e4ac in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Gui.so.5
#27 0x00007f825e354cc1 in  () at /usr/lib/libQt5XcbQpa.so.5
#28 0x00007f8266b96a57 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#29 0x00007f8266b96c88 in  () at /usr/lib/libglib-2.0.so.0
#30 0x00007f8266b96d1c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#31 0x00007f826797d061 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#32 0x00007f8267920ffb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#33 0x00007f826792a048 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#34 0x000000000041d3c3 in  ()
#35 0x00007f826621543a in __libc_start_main () at /usr/lib/libc.so.6
#36 0x00000
````

**Comment by tsujan** [comment]
OK, it happened again with the same trace. Needs investigation.

**Comment by tsujan** [comment]
I guess I started to experience it recently because only recently I've got sshd. Should be fixed by https://github.com/lxde/libfm-qt/pull/107.
